version: "3.8"
services:
    web:
        image: epmo/web
        container_name: epmo_web
        restart: always
        build:
            context: ..
            dockerfile: ./.docker/dockerfile
        environment:
            - Authentication__Schemes__Bearer__SigningKeys__1__Issuer=Issuer
            - Authentication__Schemes__Bearer__SigningKeys__1__Value=E7F87FB927DB404E9F027E0826AFF62B
            - Authentication__Schemes__Bearer__ValidAudience=Audience
            - Authentication__Schemes__Bearer__ValidIssuer=Issuer
            - ConnectionStrings__Context=Server=Epmo_database;Database=Epmo;User Id=sa;Password=P@ssW0rd!;TrustServerCertificate=true;
            - Serilog__WriteTo__1__Args__path=/app/logs/
        depends_on:
            - database
        networks:
            - network
        ports:
            - 8090:80
    database:
        image: mcr.microsoft.com/mssql/server
        container_name: Epmo_database
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssW0rd!
        networks:
            - network
        ports:
            - 1433:1433
        volumes:
            - database:/var/opt/mssql
networks:
    network:
volumes:
    database:
